-- ==============================================================================
-- OMNIBITES ENTERPRISE RESTAURANT SAAS PLATFORM
-- Migration: 20260908_settings_shift_stock_guard.sql
-- Purpose: Settings persistence, Z-Report shift settlements, and recipe stock guard
-- ==============================================================================

-- 1. Ensure public.branch_settings has all required columns and unique constraint
CREATE TABLE IF NOT EXISTS public.branch_settings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    restaurant_id BIGINT NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
    branch_id TEXT DEFAULT '1',
    tax_rate NUMERIC(5, 2) DEFAULT 16.00,
    tax_rate_percent NUMERIC(5, 2) DEFAULT 16.00,
    tax_authority_name TEXT DEFAULT 'Punjab Revenue Authority (PRA)',
    printer_ip TEXT DEFAULT '192.168.1.180',
    thermal_printer_ip TEXT DEFAULT '192.168.1.180',
    printer_paper_width TEXT DEFAULT '80mm',
    buzzer_enabled BOOLEAN DEFAULT true,
    kitchen_buzzer_enabled BOOLEAN DEFAULT true,
    opening_time TEXT DEFAULT '11:00 AM',
    closing_time TEXT DEFAULT '02:00 AM',
    currency_symbol TEXT DEFAULT 'Rs',
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.branch_settings
ADD COLUMN IF NOT EXISTS tax_rate NUMERIC(5, 2) DEFAULT 16.00,
ADD COLUMN IF NOT EXISTS tax_rate_percent NUMERIC(5, 2) DEFAULT 16.00,
ADD COLUMN IF NOT EXISTS printer_ip TEXT DEFAULT '192.168.1.180',
ADD COLUMN IF NOT EXISTS thermal_printer_ip TEXT DEFAULT '192.168.1.180',
ADD COLUMN IF NOT EXISTS printer_paper_width TEXT DEFAULT '80mm',
ADD COLUMN IF NOT EXISTS buzzer_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS kitchen_buzzer_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS opening_time TEXT DEFAULT '11:00 AM',
ADD COLUMN IF NOT EXISTS closing_time TEXT DEFAULT '02:00 AM',
ADD COLUMN IF NOT EXISTS currency_symbol TEXT DEFAULT 'Rs',
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS uq_branch_settings_restaurant ON public.branch_settings(restaurant_id);

-- 2. Ensure public.shift_settlements has all required columns
CREATE TABLE IF NOT EXISTS public.shift_settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT REFERENCES public.restaurants(id) ON DELETE CASCADE,
    branch_id BIGINT DEFAULT NULL,
    cashier_name VARCHAR(150) NOT NULL,
    shift_opened_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    shift_closed_at TIMESTAMPTZ DEFAULT NOW(),
    shift_start TIMESTAMPTZ DEFAULT NOW(),
    shift_end TIMESTAMPTZ DEFAULT NOW(),
    opening_float NUMERIC(12, 2) DEFAULT 0.00,
    cash_sales NUMERIC(12, 2) DEFAULT 0.00,
    system_cash_sales NUMERIC(12, 2) DEFAULT 0.00,
    card_sales NUMERIC(12, 2) DEFAULT 0.00,
    system_card_sales NUMERIC(12, 2) DEFAULT 0.00,
    total_gross_sales NUMERIC(12, 2) DEFAULT 0.00,
    gross_sales NUMERIC(12, 2) DEFAULT 0.00,
    expected_cash_in_drawer NUMERIC(12, 2) DEFAULT 0.00,
    actual_cash_counted NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    variance NUMERIC(12, 2) DEFAULT 0.00,
    cash_variance NUMERIC(12, 2) DEFAULT 0.00,
    notes TEXT DEFAULT '',
    closing_notes TEXT DEFAULT '',
    status VARCHAR(30) DEFAULT 'CLOSED',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.shift_settlements
ADD COLUMN IF NOT EXISTS shift_opened_at TIMESTAMPTZ DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS shift_closed_at TIMESTAMPTZ DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS opening_float NUMERIC(12, 2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS cash_sales NUMERIC(12, 2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS card_sales NUMERIC(12, 2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS total_gross_sales NUMERIC(12, 2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS expected_cash_in_drawer NUMERIC(12, 2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS actual_cash_counted NUMERIC(12, 2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS variance NUMERIC(12, 2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT '';

-- 3. Ensure public.menu_items has is_available column
ALTER TABLE public.menu_items
ADD COLUMN IF NOT EXISTS is_available BOOLEAN DEFAULT true;

UPDATE public.menu_items
SET is_available = (stock_status = 'in_stock')
WHERE is_available IS NULL;
