-- ==============================================================================
-- OMNIBITES ENTERPRISE RESTAURANT SAAS PLATFORM
-- Migration: 20260907_restaurant_tables.sql
-- Table: public.restaurant_tables (Part 2.1: Table & Floor Management)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.restaurant_tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT REFERENCES public.restaurants(id) ON DELETE CASCADE,
    branch_id BIGINT DEFAULT NULL,
    table_number VARCHAR(50) NOT NULL,
    section_name VARCHAR(60) DEFAULT 'Main Dining', -- e.g., Ground Floor, Family Hall, Terrace, Outdoor
    seating_capacity INT DEFAULT 4,
    status VARCHAR(30) DEFAULT 'AVAILABLE',          -- AVAILABLE, OCCUPIED, RESERVED, BILLED
    current_order_id BIGINT DEFAULT NULL,
    active_covers INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Resilient column alignment if table was created previously with earlier schema variants
ALTER TABLE public.restaurant_tables ADD COLUMN IF NOT EXISTS section_name VARCHAR(60) DEFAULT 'Main Dining';
ALTER TABLE public.restaurant_tables ADD COLUMN IF NOT EXISTS seating_capacity INT DEFAULT 4;
ALTER TABLE public.restaurant_tables ADD COLUMN IF NOT EXISTS active_covers INT DEFAULT 0;
ALTER TABLE public.restaurant_tables ADD COLUMN IF NOT EXISTS current_order_id BIGINT DEFAULT NULL;
ALTER TABLE public.restaurant_tables ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_restaurant_tables_tenant ON public.restaurant_tables(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_restaurant_tables_status ON public.restaurant_tables(status);

ALTER TABLE public.restaurant_tables ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant Tables Access" ON public.restaurant_tables;
CREATE POLICY "Tenant Tables Access" ON public.restaurant_tables FOR ALL USING (true);
