-- ==============================================================================
-- OMNIBITES ENTERPRISE RESTAURANT SAAS PLATFORM
-- Migration: 20260907_shift_settlements.sql
-- Table: public.shift_settlements (Part 3.2: Shift Settlement & Z-Report Engine)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.shift_settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT REFERENCES public.restaurants(id) ON DELETE CASCADE,
    branch_id BIGINT DEFAULT NULL,
    cashier_name VARCHAR(100) NOT NULL,
    shift_start TIMESTAMPTZ NOT NULL,
    shift_end TIMESTAMPTZ DEFAULT NOW(),
    opening_float NUMERIC(12, 2) DEFAULT 0,       -- Initial cash in drawer
    system_cash_sales NUMERIC(12, 2) DEFAULT 0,
    system_card_sales NUMERIC(12, 2) DEFAULT 0,
    system_digital_sales NUMERIC(12, 2) DEFAULT 0,
    total_tax_collected NUMERIC(12, 2) DEFAULT 0,
    total_discounts NUMERIC(12, 2) DEFAULT 0,
    gross_sales NUMERIC(12, 2) DEFAULT 0,
    total_orders_count INT DEFAULT 0,
    actual_cash_counted NUMERIC(12, 2) NOT NULL,  -- Physical cash counted by cashier
    cash_variance NUMERIC(12, 2) DEFAULT 0,       -- actual_cash - (opening_float + system_cash)
    status VARCHAR(30) DEFAULT 'CLOSED',          -- OPEN, CLOSED, AUDITED
    closing_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_shift_settlements_tenant ON public.shift_settlements(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_shift_settlements_created ON public.shift_settlements(created_at);

ALTER TABLE public.shift_settlements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant Shift Settlements Access" ON public.shift_settlements;
CREATE POLICY "Tenant Shift Settlements Access" ON public.shift_settlements FOR ALL USING (true);
