-- ==============================================================================
-- OMNIBITES ENTERPRISE RESTAURANT SAAS PLATFORM
-- Migration: 20260907_procurement.sql
-- Tables: public.suppliers, public.purchase_orders (Part 4.1: Procurement System)
-- ==============================================================================

-- 1. Suppliers Registry Table
CREATE TABLE IF NOT EXISTS public.suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT REFERENCES public.restaurants(id) ON DELETE CASCADE,
    branch_id BIGINT DEFAULT NULL,
    name VARCHAR(150) NOT NULL,
    contact_person VARCHAR(100),
    phone VARCHAR(50),
    email VARCHAR(100),
    category VARCHAR(60) DEFAULT 'General', -- Meat, Dairy, Produce, Packaging
    payment_terms VARCHAR(50) DEFAULT 'Cash on Delivery', -- Net 15, Net 30, COD
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Purchase Orders Table
CREATE TABLE IF NOT EXISTS public.purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT REFERENCES public.restaurants(id) ON DELETE CASCADE,
    branch_id BIGINT DEFAULT NULL,
    po_number VARCHAR(50) NOT NULL, -- e.g. PO-2026-001
    supplier_id BIGINT REFERENCES public.suppliers(id) ON DELETE RESTRICT,
    supplier_name VARCHAR(150),
    status VARCHAR(30) DEFAULT 'PENDING', -- PENDING, APPROVED, RECEIVED, CANCELLED
    total_cost NUMERIC(12, 2) DEFAULT 0,
    items JSONB NOT NULL DEFAULT '[]'::jsonb, -- [{raw_material_id, name, unit, unit_price, quantity, subtotal}]
    notes TEXT,
    expected_delivery DATE,
    created_by VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_suppliers_tenant ON public.suppliers(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_tenant ON public.purchase_orders(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_status ON public.purchase_orders(status);

ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant Suppliers Access" ON public.suppliers;
CREATE POLICY "Tenant Suppliers Access" ON public.suppliers FOR ALL USING (true);

ALTER TABLE public.purchase_orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant PO Access" ON public.purchase_orders;
CREATE POLICY "Tenant PO Access" ON public.purchase_orders FOR ALL USING (true);
