-- ==============================================================================
-- OMNIBITES ENTERPRISE RESTAURANT SAAS PLATFORM
-- Migration: 20260907_recipe_items.sql
-- Table: public.recipe_items (Part 1.2: Recipe / BOM Linking)
-- ==============================================================================

DO $$
DECLARE
    col_type text;
BEGIN
    -- Check column type of public.menu_items.id to prevent foreign key type mismatch
    SELECT data_type INTO col_type
    FROM information_schema.columns
    WHERE table_schema = 'public' 
      AND table_name = 'menu_items' 
      AND column_name = 'id';

    IF col_type = 'uuid' THEN
        CREATE TABLE IF NOT EXISTS public.recipe_items (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            restaurant_id BIGINT REFERENCES public.restaurants(id) ON DELETE CASCADE,
            menu_item_id UUID REFERENCES public.menu_items(id) ON DELETE CASCADE,
            raw_material_id BIGINT REFERENCES public.raw_materials(id) ON DELETE CASCADE,
            quantity_required NUMERIC(10, 3) NOT NULL, -- e.g., 0.150 (for 150g chicken), 1 (for 1 bun)
            unit VARCHAR(20) NOT NULL,                 -- Unit snapshot matching raw material
            created_at TIMESTAMPTZ DEFAULT NOW()
        );
    ELSE
        CREATE TABLE IF NOT EXISTS public.recipe_items (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            restaurant_id BIGINT REFERENCES public.restaurants(id) ON DELETE CASCADE,
            menu_item_id BIGINT REFERENCES public.menu_items(id) ON DELETE CASCADE,
            raw_material_id BIGINT REFERENCES public.raw_materials(id) ON DELETE CASCADE,
            quantity_required NUMERIC(10, 3) NOT NULL,
            unit VARCHAR(20) NOT NULL,
            created_at TIMESTAMPTZ DEFAULT NOW()
        );
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_recipe_items_menu_item ON public.recipe_items(menu_item_id);
CREATE INDEX IF NOT EXISTS idx_recipe_items_raw_material ON public.recipe_items(raw_material_id);
CREATE INDEX IF NOT EXISTS idx_recipe_items_restaurant ON public.recipe_items(restaurant_id);

ALTER TABLE public.recipe_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant Recipe Items Access" ON public.recipe_items;
CREATE POLICY "Tenant Recipe Items Access" ON public.recipe_items FOR ALL USING (true);
