-- ==============================================================================
-- OMNIBITES ENTERPRISE RESTAURANT SAAS PLATFORM
-- Migration: 20260907_raw_materials.sql
-- Table: public.raw_materials (Part 1.1: Raw Materials Registry)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.raw_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT REFERENCES public.restaurants(id) ON DELETE CASCADE,
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE SET NULL,
    name VARCHAR(150) NOT NULL,
    sku VARCHAR(60),
    category VARCHAR(60) DEFAULT 'General', -- e.g. Meat, Dairy, Produce, Bakery, Packaging
    unit VARCHAR(20) NOT NULL,              -- e.g. kg, g, ltr, ml, pcs
    current_stock NUMERIC(12, 3) DEFAULT 0,
    min_safety_stock NUMERIC(12, 3) DEFAULT 5,
    cost_per_unit NUMERIC(10, 2) DEFAULT 0, -- Used for COGS calculation
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexing for fast multi-tenant queries
CREATE INDEX IF NOT EXISTS idx_raw_materials_restaurant_id ON public.raw_materials(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_raw_materials_branch_id ON public.raw_materials(branch_id);

-- Enable RLS & simple policies
ALTER TABLE public.raw_materials ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE schemaname = 'public' 
      AND tablename = 'raw_materials' 
      AND policyname = 'Tenant Raw Materials Access'
  ) THEN
    CREATE POLICY "Tenant Raw Materials Access" ON public.raw_materials
        FOR ALL USING (true);
  END IF;
END $$;
